In [1]:
import numpy as np

### Matrices

In [2]:
matrix = np.arange(1, 13).reshape(3, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [4]:
(matrix[0, :] + matrix[2, :]) / 2

array([5., 6., 7., 8.])

### Right-multipy & left-multiply

In [5]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
matrix @ np.array([1000, 100, 10, 1])

array([ 1234,  5678, 10122])

In [7]:
np.array([0, 0.1, 1]) @ matrix

array([ 9.5, 10.6, 11.7, 12.8])

### Singular value decomposition

In [8]:
u, s, vt = np.linalg.svd(matrix, full_matrices=False)
print('u:', u.shape, 'v:', vt.T.shape, 's:', s)

u: (3, 3) v: (4, 3) s: [2.54368356e+01 1.72261225e+00 5.14037515e-16]


In [9]:
u * s

array([[-5.25870689e+00, -1.53166638e+00,  2.09854937e-16],
       [-1.31836254e+01, -4.38201263e-01, -4.19709874e-16],
       [-2.11085440e+01,  6.55263852e-01,  2.09854937e-16]])

In [10]:
Us = (u * s)[:, :2]
Us

array([[ -5.25870689,  -1.53166638],
       [-13.18362544,  -0.43820126],
       [-21.10854399,   0.65526385]])

In [11]:
Vt = vt[:2, :]
Vt

array([[-0.40361757, -0.46474413, -0.52587069, -0.58699725],
       [ 0.73286619,  0.28984978, -0.15316664, -0.59618305]])

In [12]:
print('Us:', Us.shape, 'Vt:', Vt.shape)
Us @ Vt

Us: (3, 2) Vt: (2, 4)


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [13]:
np.round(u @ u.T, 10)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

In [14]:
np.round(vt @ vt.T, 10)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [15]:
v = vt.T
matrix @ v

array([[-5.25870689e+00, -1.53166638e+00, -5.55111512e-16],
       [-1.31836254e+01, -4.38201263e-01, -1.11022302e-16],
       [-2.11085440e+01,  6.55263852e-01,  3.33066907e-16]])

In [16]:
u * s

array([[-5.25870689e+00, -1.53166638e+00,  2.09854937e-16],
       [-1.31836254e+01, -4.38201263e-01, -4.19709874e-16],
       [-2.11085440e+01,  6.55263852e-01,  2.09854937e-16]])

In [19]:
np.diag(s)

array([[2.54368356e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.72261225e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.14037515e-16]])

In [20]:
u @ np.diag(s) @ vt

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])